// Code generated by hertz generator.

package ZgsServiceDiscovery

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list_gentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _update_gentextMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateonline_gentsgroupMw() []app.HandlerFunc {
	// your code...
	return nil
}
