// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/Albatrossiun/zgs_service_discovery/biz/dao"
	"github.com/Albatrossiun/zgs_service_discovery/biz/handler/zgs_service_discovery"
	"github.com/Albatrossiun/zgs_service_discovery/biz/storage"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	err := storage.InitRedisPool()
	if err != nil {
		fmt.Println("err = ", err)
		return
	}
	dao.InitRedis()
	dao.InitUserRepository()
	zgs_service_discovery.InitUserServiceHandler()
	//backstage.StartHeartbeat()

	register(h)
	h.Spin()
}
