// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	zgs_service_discovery "github.com/Albatrossiun/zgs_service_discovery/biz/router/zgs_service_discovery"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	zgs_service_discovery.Register(r)
}
